=begin
#Talis Blueprint API

#This is the API documentation for [Blueprint](https://github.com/talis/blueprint-server), a primitive for institutional structure and time periods

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for BlueprintClient::AssetTypeTemplatesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AssetTypeTemplatesApi' do
  before do
    # run before each test
    @instance = BlueprintClient::AssetTypeTemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssetTypeTemplatesApi' do
    it 'should create an instact of AssetTypeTemplatesApi' do
      expect(@instance).to be_instance_of(BlueprintClient::AssetTypeTemplatesApi)
    end
  end

  # unit tests for add
  # 
  # Configure a template for a given asset type
  # @param namespace identifier namespacing the blueprint.
  # @param asset_type subtype of Asset, e.g. &#39;textbooks&#39;, &#39;digitisations&#39;, etc.
  # @param template_body template body
  # @param [Hash] opts the optional parameters
  # @return [TemplateBody]
  describe 'add test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # 
  # Delete a template for a given asset type
  # @param namespace identifier namespacing the blueprint.
  # @param asset_type subtype of Asset, e.g. &#39;textbooks&#39;, &#39;digitisations&#39;, etc.
  # @param [Hash] opts the optional parameters
  # @return [TemplateBody]
  describe 'delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put
  # 
  # update a template for a given asset type
  # @param namespace identifier namespacing the blueprint.
  # @param asset_type subtype of Asset, e.g. &#39;textbooks&#39;, &#39;digitisations&#39;, etc.
  # @param template_body template body
  # @param [Hash] opts the optional parameters
  # @return [TemplateBody]
  describe 'put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
