=begin
Talis Blueprint API

This is the API documentation for [Blueprint](https://github.com/talis/blueprint-server), a primitive for institutional structure and time periods

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for BlueprintClient::LTIApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LTIApi' do
  before do
    # run before each test
    @instance = BlueprintClient::LTIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LTIApi' do
    it 'should create an instact of LTIApi' do
      @instance.should be_a(BlueprintClient::LTIApi)
    end
  end

  # unit tests for namespace_integrations_lti1_integration_id_assets_asset_type_asset_id_post
  # 
  # LTI launch url for integration
  # @param namespace identifier namespacing the blueprint.
  # @param integration_id id of an integration
  # @param asset_type subtype of Asset, e.g. &#39;textbooks&#39;, &#39;digitisations&#39;, etc.
  # @param asset_id id of an asset
  # @param lti_message_type LTI launch data message type, must be &#39;basic-lti-launch-request&#39;
  # @param lti_version LTI launch version, must be &#39;LTI-1p0&#39;
  # @param resource_link_id LTI resource_link_id parameters
  # @param [Hash] opts the optional parameters
  # @option opts [String] :oauth_consumer_key OAuth 1.0 consumer_key parameters
  # @option opts [String] :oauth_consumer_key2 OAuth 1.0 consumer_key parameters
  # @option opts [String] :oauth_signature_method OAuth 1.0 signature method, must be &#39;HMAC-SHA1&#39;
  # @option opts [String] :oauth_signature_method2 OAuth 1.0 signature method, must be &#39;HMAC-SHA1&#39;
  # @option opts [Integer] :oauth_timestamp OAuth 1.0 timestamp of request
  # @option opts [Integer] :oauth_timestamp2 OAuth 1.0 timestamp of request
  # @option opts [Float] :oauth_version OAuth 1.0 version, must be &#39;1.0&#39;
  # @option opts [Float] :oauth_version2 OAuth 1.0 version, must be &#39;1.0&#39;
  # @option opts [String] :oauth_nonce OAuth 1.0 Nonce
  # @option opts [String] :oauth_nonce2 OAuth 1.0 Nonce
  # @option opts [String] :oauth_signature OAuth 1.0 request signature
  # @option opts [String] :oauth_signature2 OAuth 1.0 request signature
  # @return [nil]
  describe 'namespace_integrations_lti1_integration_id_assets_asset_type_asset_id_post test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
