=begin
Talis Blueprint API

This is the API documentation for [Blueprint](https://github.com/talis/blueprint-server), a primitive for institutional structure and time periods

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BlueprintClient::AssetRelationships
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AssetRelationships' do
  before do
    # run before each test
    @instance = BlueprintClient::AssetRelationships.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssetRelationships' do
    it 'should create an instact of AssetRelationships' do
      @instance.should be_a(BlueprintClient::AssetRelationships) 
    end
  end
  describe 'test attribute "nodes"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

