=begin
Talis Blueprint API

This is the API documentation for [Blueprint](https://github.com/talis/blueprint-server), a primitive for institutional structure and time periods

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BlueprintClient::Lti1IntegrationAttributes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Lti1IntegrationAttributes' do
  before do
    # run before each test
    @instance = BlueprintClient::Lti1IntegrationAttributes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Lti1IntegrationAttributes' do
    it 'should create an instact of Lti1IntegrationAttributes' do
      @instance.should be_a(BlueprintClient::Lti1IntegrationAttributes) 
    end
  end
  describe 'test attribute "consumer_key"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "shared_secret"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "taught_unit_type"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "transforms"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

