=begin
Talis Blueprint API

This is the API documentation for [Blueprint](https://github.com/talis/blueprint-server), a primitive for institutional structure and time periods

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

# Common files
require 'blueprint_rb/api_client'
require 'blueprint_rb/api_error'
require 'blueprint_rb/version'
require 'blueprint_rb/configuration'

# Models
require 'blueprint_rb/models/asset'
require 'blueprint_rb/models/asset_body'
require 'blueprint_rb/models/asset_result_set'
require 'blueprint_rb/models/error'
require 'blueprint_rb/models/errors'
require 'blueprint_rb/models/links'
require 'blueprint_rb/models/meta'
require 'blueprint_rb/models/namespace'
require 'blueprint_rb/models/namespace_relationship'
require 'blueprint_rb/models/node'
require 'blueprint_rb/models/node_attributes'
require 'blueprint_rb/models/node_body'
require 'blueprint_rb/models/node_relationship'
require 'blueprint_rb/models/node_relationships'
require 'blueprint_rb/models/node_result_set'

# APIs
require 'blueprint_rb/api/assets_api'
require 'blueprint_rb/api/hierarchy_api'

module BlueprintClient
  class << self
    # Customize default settings for the SDK using block.
    #   BlueprintClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
